### PR TITLE
fix: make http fetch wait 2s

### LINKED ISSUE #5: HTTP deadline to be set in Config
The http deadline is currently hardcoded, move this to the pallet config

### PR DESCRIPTION
**Pull request by juangirini**
closes #5 

- make http fetch wait 2s
- de duplicate code
- add extra warning to `fetch_drand`

### CODE REVIEW

File: pallets/drand/src/lib.rs [hunk 1]
```diff
@@ -599,10 +599,21 @@ impl<T: Config> Pallet<T> {
...
+		Self::fetch(uri)
+	}
+
+	/// Fetch a remote URL and return the body of the response as a string.
+	fn fetch(uri: &str) -> Result<String, http::Error> {
 		// TODO: move this value to config
 		// https://github.com/ideal-lab5/pallet-drand/issues/5
-		let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(1_000));
-		let uri: &str = &format!("{}/{}/info", API_ENDPOINT, QUICKNET_CHAIN_HASH);
+		let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(2_000));
```
Comment (driemworks) [inline pallets/drand/src/lib.rs:616]: What if we made the wait time configurable? something like T::HttpFetchTimeout?

**Review by driemworks — APPROVED** [review]

File: pallets/drand/src/lib.rs (hunk 1 above)
Comment (juangirini) [reply pallets/drand/src/lib.rs:616]: yes, that's this issue https://github.com/ideal-lab5/pallet-drand/issues/5
but good point, we can include it as part of it
